baseURL = '/'
languageCode = 'en-us'
title = 'Shaun Luttin, NrD'
theme = 'PaperMod'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "other"
    name = "Other Web Presence"
    url = "/other-web/"
    weight = 2
