baseURL = '/'
languageCode = 'en-us'
title = 'Shaun Luttin, NrD'
theme = 'classless-blog'

[menu]

  [[menu.main]]
    identifier = "other"
    name = "Other Web Presence"
    url = "/other-web/"
    weight = 10
